version: '3'

services:
  snippet-runner:
    container_name: "snippet-runner"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
        - .:/app/data
