version: '3'

services:
  snippet-runner-standalone:
    container_name: "snippet-runner-standalone"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
        - .:/app/data
