name: "Continuous Deployment Master"

on:
  workflow_run:
    workflows: [ "Java CI with Gradle" ]
    branches:
      - master
    types:
      - completed

jobs:
  push_snippet_runner:
    name: Push snippet-runner image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/ingsis-group2/snippet-runner-master:latest
          build-args: |
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_MASTER }}
          username: "azureuser"
          key: ${{ secrets.PRIVATE_KEY_MASTER }}
          script: |
            cd snippet-infra
            docker compose -f docker-compose.master.yml stop snippet-runner
            docker compose -f docker-compose.master.yml up snippet-runner -d --build 
